---
- hosts: all
  gather_facts: true
  tasks:
  - name: Ping host
    ping:
    register: ping

  - name: Check Server Status
    block:
    - debug:
        msg: "Server is up"
      when: "'pong' in ping.ping"

    - debug:
        msg: "Server is  not up"
      when: "'pong' not in ping.ping"
